[package]
name = "denispionicul/stater"
version = "0.5.0"
registry = "https://github.com/UpliftGames/wally-index"
description = "A finite state machine module with a lot of features and customisability."
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@1.0.1"
Signal = "sleitnick/signal@1.5.0"
Option = "sleitnick/option@1.0.4"	
Promise = "evaera/promise@^4"